#!/usr/bin/env node
// Meridian Skills MCP — stdio client for ask-meridian.uk's orbital router.
//
// All routing happens server-side: the public endpoint generates skill
// candidates with Llama-3.3-70B and classifies them with the open-domain
// orbital engine (planet / moon / trojan / asteroid / comet / irregular).
//
// This client is intentionally tiny — no local model, no curated corpus,
// no Python. One stdio MCP server, one HTTP POST per call.

import { Server }              from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js'

const API_URL  = process.env.MERIDIAN_API_URL  || 'https://ask-meridian.uk/api/orbital-route'
const API_KEY  = process.env.MERIDIAN_API_KEY  || ''
const TIMEOUT  = parseInt(process.env.MERIDIAN_TIMEOUT_MS || '90000', 10)

const server = new Server(
  { name: 'meridian-skills', version: '1.0.0' },
  { capabilities: { tools: {} } },
)

const TOOLS = [
  {
    name: 'route_task',
    description:
      'Route a task to the most relevant skills. Skills are generated by Llama-3.3-70B and classified by the orbital engine into celestial classes (planet / moon / trojan / asteroid / comet / irregular). Each result includes the full skill body, classification metadata, physics signature, and decision rule. ⚠ Each call typically takes 30–50 seconds. Returns at most `limit` skills (default 5).',
    inputSchema: {
      type: 'object',
      properties: {
        task:  { type: 'string',  description: 'Task / question / context. Up to 800 chars.' },
        limit: { type: 'integer', description: 'Max skills to return (1–10, default 5)', default: 5 },
      },
      required: ['task'],
    },
  },
]

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const { name, arguments: args } = req.params
  if (name !== 'route_task') {
    return { content: [{ type: 'text', text: `Unknown tool: ${name}` }], isError: true }
  }

  const task  = (args.task || '').toString().trim()
  const limit = Math.max(1, Math.min(10, parseInt(args.limit, 10) || 5))
  if (!task)             return errorContent('task required')
  if (task.length > 800) return errorContent('task too long (max 800)')

  try {
    const result = await callBackend({ task, limit })
    return {
      content: [
        {
          type: 'text',
          text: formatResult(result),
        },
      ],
    }
  } catch (e) {
    return errorContent(`Backend error: ${e.message || e}`)
  }
})

async function callBackend({ task, limit }) {
  const ctrl = new AbortController()
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT)
  try {
    const res = await fetch(API_URL, {
      method:  'POST',
      headers: {
        'content-type': 'application/json',
        ...(API_KEY ? { 'authorization': `Bearer ${API_KEY}` } : {}),
        'user-agent': 'meridian-skills-mcp/1.0.0',
      },
      body:   JSON.stringify({ task, limit }),
      signal: ctrl.signal,
    })
    const body = await res.json().catch(() => ({}))
    if (!res.ok) throw new Error(body.error || `HTTP ${res.status}`)
    return body
  } catch (e) {
    if (e.name === 'AbortError') throw new Error(`timeout after ${TIMEOUT} ms (set MERIDIAN_TIMEOUT_MS to increase)`)
    throw e
  } finally {
    clearTimeout(timer)
  }
}

function formatResult(r) {
  // Render a compact, agent-readable digest. Body content stays full so the
  // caller LLM can lift the skills directly into its context window.
  const header = [
    `# Orbital routing result`,
    `Task: ${r.task}`,
    `Confidence: ${r.confidence}  ·  top score ${r.top_score?.toFixed?.(1) ?? '?'}`,
    r.timing ? `Timing: LLM ${r.timing.llm_ms} ms · classify ${r.timing.classify_ms} ms` : '',
    `${r.selected?.length ?? 0} skill(s) selected`,
    '',
  ].filter(Boolean).join('\n')

  const skills = (r.selected || []).map((s, i) => {
    const c = s.classification || {}
    const meta = [
      `class: ${c.class || '?'}`,
      c.parent ? `parent: ${c.parent}`           : null,
      c.star_system ? `system: ${c.star_system}` : null,
      `score: ${s.route_score?.toFixed?.(1) ?? '?'}`,
    ].filter(Boolean).join('  ·  ')

    return [
      `## ${i + 1}. ${s.slug}`,
      `${meta}`,
      c.decision_rule ? `> ${c.decision_rule}` : '',
      '',
      s.description || '',
      '',
      s.body || '',
      s.keywords?.length
        ? `\n**keywords**: ${s.keywords.map(k => '`' + k + '`').join(' ')}`
        : '',
      '',
    ].filter(Boolean).join('\n')
  }).join('\n---\n\n')

  return header + skills
}

function errorContent(msg) {
  return { content: [{ type: 'text', text: `Error: ${msg}` }], isError: true }
}

const transport = new StdioServerTransport()
await server.connect(transport)
