"""
Run all three verifications and emit a single consolidated proof.md
that's commit-able alongside the code.

Exits non-zero if residency or parity fails. Latency is informational
only (Python predict() overhead obscures it on tiny models).
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


def run(cmd: list[str]) -> tuple[int, str]:
    p = subprocess.run(cmd, capture_output=True, text=True)
    out = p.stdout + p.stderr
    return p.returncode, out


def main(mlpackage_path: str) -> int:
    pkg = Path(mlpackage_path)
    if not pkg.exists():
        print(f"error: {pkg} does not exist", file=sys.stderr)
        return 2

    here = Path(__file__).parent
    py = str(here / ".venv" / "bin" / "python")

    print("[1/4] static residency (op-allowlist) ...")
    rc1, out1 = run([py, str(here / "verify_residency.py"), str(pkg)])
    print("[2/4] numeric parity (PyTorch vs CoreML) ...")
    rc2, out2 = run([py, str(here / "verify_parity.py"), str(pkg)])
    print("[3/4] latency benchmark (informational) ...")
    rc3, out3 = run([py, str(here / "verify_latency.py"), str(pkg)])

    # Step 4: runtime compute-plan via MLComputePlan. Requires the
    # compiled .mlmodelc form, not the .mlpackage. Build it on demand.
    print("[4/4] runtime compute plan (Swift / MLComputePlan) ...")
    mlmodelc = pkg.parent / pkg.name.replace(".mlpackage", ".mlmodelc")
    if not mlmodelc.exists():
        rcC, outC = run(["xcrun", "coremlcompiler", "compile", str(pkg), str(pkg.parent)])
        if rcC != 0:
            print("  coremlcompiler failed:")
            print(outC)
    rc4, out4 = run(["swift", str(here / "inspect_ane.swift"), str(mlmodelc)])

    proof_dir = pkg.parent / "proof"
    proof_dir.mkdir(exist_ok=True)
    meta_path = pkg.parent / "build_meta.json"
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}

    md = []
    md.append(f"# ANE residency proof — {pkg.name}\n")
    md.append(f"Generated by `verify_all.py`. coremltools={meta.get('coremltools', '?')}, "
              f"torch={meta.get('torch', '?')}.\n")

    # Pull runtime ANE % from the JSON the Swift inspector wrote
    runtime_pct = None
    runtime_json = proof_dir / "runtime_plan.json"
    if runtime_json.exists():
        try:
            runtime_pct = json.loads(runtime_json.read_text()).get("ane_residency_pct")
        except Exception:
            pass

    md.append("## Verdict\n")
    md.append(f"- Static op-allowlist: **{'PASS' if rc1 == 0 else 'FAIL'}** (every op in MIL is on the ANE allowlist)")
    md.append(f"- Numeric parity:      **{'PASS' if rc2 == 0 else 'FAIL'}** (CoreML FP16 ≡ PyTorch FP32 within tolerance)")
    md.append(f"- Runtime placement:   **{'PASS' if rc4 == 0 else 'FAIL'}** "
              f"(MLComputePlan: **{runtime_pct:.1f}%** of schedulable ops preferred ANE)"
              if runtime_pct is not None else
              f"- Runtime placement:   **{'PASS' if rc4 == 0 else 'FAIL'}** (see runtime_plan.json)")
    md.append("- Latency benchmark:   informational (Python `predict()` overhead "
              "obscures ANE win on tiny models — Swift / MLComputePlan above is the load-bearing runtime proof)\n")

    md.append("## Static residency (strongest signal)\n")
    md.append("Parses the MIL spec and checks every op against the ANE-eligible allowlist.\n")
    md.append("```")
    md.append((proof_dir / "residency.txt").read_text().rstrip())
    md.append("```\n")

    md.append("## Numeric parity\n")
    md.append("PyTorch FP32 baseline vs CoreML FP16 output, combined-tolerance "
              "(`|a-b| <= atol + rtol*|b|`).\n")
    md.append("```")
    md.append((proof_dir / "parity.txt").read_text().rstrip())
    md.append("```\n")

    md.append("## Runtime latency (informational)\n")
    md.append("CPU_ONLY vs CPU_AND_NE wall-time. **Note**: at this demo model size "
              "(2 layers × 128 dim × 64 tokens, ~800 KB on disk) the Python→ObjC "
              "`predict()` call overhead (~0.5 ms) dominates the per-call cost. "
              "ANE compute itself is microseconds. A meaningful speedup needs either "
              "(a) a 150M+ param model — the strategic target, ESM2 — or "
              "(b) the Xcode performance report, which measures the compiled "
              "program directly rather than going through Python.\n")
    md.append("```")
    md.append((proof_dir / "latency.txt").read_text().rstrip())
    md.append("```\n")

    md.append("## Runtime compute plan (MLComputePlan) — authoritative\n")
    md.append("Programmatic equivalent of the Xcode Performance Report's per-op breakdown. "
              "Loads the compiled .mlmodelc with `computeUnits=.cpuAndNeuralEngine`, asks "
              "CoreML for the runtime device assignment of every op.\n")
    md.append("```")
    md.append((proof_dir / "runtime_plan.json").read_text().rstrip()
              if (proof_dir / "runtime_plan.json").exists()
              else "(missing — run `swift inspect_ane.swift build/AneEncoder.mlmodelc`)")
    md.append("```\n")

    md.append("## Cross-check with Xcode (optional, same data)\n")
    md.append("```bash")
    md.append(f"open {pkg}")
    md.append("# Xcode opens. Performance tab. Set Compute Units to 'CPU and Neural Engine'.")
    md.append("# The 'Compute Unit' column shows the per-op runtime assignment.")
    md.append("```\n")

    md.append("## Recipe reminder\n")
    md.append("The four constraints satisfied here, applied identically:\n")
    md.append("1. **Precision** — `compute_precision=ct.precision.FLOAT16` in convert.py.")
    md.append("2. **Layout**    — `(B, C, 1, S)`, all linear ops are `nn.Conv2d(in, out, 1)`.")
    md.append("3. **Operators** — split-axis LayerNorm, tanh-GELU, attention rewritten without bmm/einsum, no concat.")
    md.append("4. **Shapes**    — batch+dim+dummy axis static; sequence is `ct.RangeDim(32, 256)`.\n")

    (proof_dir / "proof.md").write_text("\n".join(md))
    print(f"\n[write] {proof_dir / 'proof.md'}")

    summary_rc = rc1 | rc2 | rc4  # latency is informational
    if summary_rc == 0:
        rt_str = f"runtime {runtime_pct:.1f}% on ANE" if runtime_pct is not None else "runtime PASS"
        print(f"\nOVERALL: PASS — static 100% + parity 0 violations + {rt_str}.")
    return summary_rc


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "build/AneEncoder.mlpackage"
    sys.exit(main(path))
